cc_binary(
    name = "main",
    srcs = ["main.cc"],
    # includes = [
    #     "/home/xiaochen/code/libpg_query",
    # ],
    # linkopts = [
    #     "-L/home/xiaochen/code/libpg_query",
    #     "-lpg_query",
    # ],
    visibility = ["//visibility:public"],
    deps = [
        # "//:libpg_query",
        "//:spdlog",
    ],
)
