#!/usr/bin/env bash

set -o xtrace
set -o errexit
set -o nounset

cmake --version
clang++ --version

sudo apt install -y \
    libpq-dev \
    libpqxx-dev

cmake --preset=debug
cmake --build ./build/debug
