#!/usr/bin/env bash

set -o xtrace
set -o errexit
set -o nounset

cmake --version
clang++ --version

sudo apt-get install -y \
    libpq-dev \
    libpqxx-dev

ls -l ~/local/cpplib/lib/libabsl_base*

cmake --preset=debug
cmake --build ./build/debug
