#!/usr/bin/env bash

set -o xtrace
set -o errexit
set -o nounset

# install dependencies
curl -LsSf https://astral.sh/uv/install.sh | sh
uv tool install cpplint

# run cpplint
uv run ./scripts/format/run-cpplint.py