#!/usr/bin/env bash

set -o xtrace
set -o errexit
set -o nounset

# install dependencies
sudo apt install -y \
    libpq-dev \
    libpqxx-dev

# configure cmake
cmake --preset=debug

# build all targets
cmake --build ./build/debug
