cc_library(
    name = "query",
    srcs = [
        "query.cc",
    ],
    hdrs = ["query.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//:arrow",
        "//:spdlog",
    ],
)
