cc_binary(
    name = "main",
    srcs = ["log.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//:spdlog",
    ],
)

cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
)