cc_test(
    name = "sql_test",
    size = "small",
    srcs = ["sql_test.cc"],
    deps = [
        "//:spdlog",
        "//:libpqxx",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
