name: build

on:
  push:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: ./scripts/ci/lint

      - name: Build
        run: ./scripts/ci/build

      - name: Test
        run: ./scripts/ci/test
