name: build

on:
  push:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: ./scripts/ci/install-deps

      - name: Build
        run: ./play/scripts/build
